### ISSUE TITLE
Drone Control

### ISSUE THREAD

**Issue by shadkhan12** [simmubhangu/pluto_drone#6]
Is the drone flight path predefined in ROS?Can we achieve Swarming without the use of camera and yet achieve stable swarm?How to link the ROS to Pluto?

**Comment by simmubhangu** [comment]
You can do that also. You can swarm the drone but the main problem is the holding/localization the position of drone. For that you need some feedback to hold the position of drone at particular coordinate. if you have any other method of localization you don't need camera. 

ROS and pluto are connecting using wifi and multiwii protocol is used for command communications.

**Comment by shadkhan12** [comment]
would you please share the swarm video that you implemented

**Comment by shadkhan12** [comment]
where can i buy the camera for pluto .. as the package that i ordered
doesn't have one and I suppose not any camera would be compatible.

**Comment by simmubhangu** [comment]
Here is the video link :https://www.youtube.com/watch?v=byYLyB6in58&feature=youtu.be

You can buy any USB camera. make sure the FPS and resolution of camera is good. we have used [this camera](https://www.aliexpress.com/item/2MP-CMOS-OV2710-High-30-60-120-fps-Industrial-Mini-1-05mm-Wide-angle-fisheye-lens/32727795207.html?spm=2114.search0104.3.17.471a19d9wM3hYV&ws_ab_test=searchweb0_0,searchweb201602_7_10065_10068_319_10059_10884_317_10887_10696_321_322_10084_453_10083_454_10103_10618_10307_537_536_10902,searchweb201603_35,ppcSwitch_0&algo_expid=22fa091a-40ab-4dc3-a9d9-248636b57d12-2&algo_pvid=22fa091a-40ab-4dc3-a9d9-248636b57d12)
